#!/usr/bin/env python3
"""Group work/risky_cmds.jsonl (from cmd_scan.py) into work/risky_digest.md for the verification lane.
Usage: risky_digest.py ./work [--max-groups 40] [--examples 3]

Per risk pattern: hit count, distinct command groups (dedupe key = command with digits/hashes stripped, first
80 chars), and for each group: count, first/last timestamp, projects, nested/codex flags, example commands.
Raw hits are mostly noise (greps for the words, patch bodies, prose); the lane's job is to triage, so the
digest keeps enough context to do that and never becomes a report by itself.
"""
import os, sys, json, re, argparse, collections

STRIP = re.compile(r'[0-9a-f]{7,}|\d+')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('work')
    ap.add_argument('--max-groups', type=int, default=40)
    ap.add_argument('--examples', type=int, default=3)
    a = ap.parse_args()
    src = os.path.join(a.work, 'risky_cmds.jsonl')
    hits = [json.loads(l) for l in open(src)] if os.path.exists(src) else []
    by_pat = collections.defaultdict(list)
    for h in hits:
        for k in h['hits']:
            by_pat[k].append(h)
    out = [f"# risky command digest — {len(hits):,} raw hits, {len(by_pat)} patterns. Generated by risky_digest.py",
           "Each hit is a shell command some tool issued (Claude Bash / Codex exec). Greps for the words, patch bodies and prose match too — "
           "triage before quoting any count. Timestamps are UTC. `nested` = issued by a sub-agent.", ""]
    for pat, hs in sorted(by_pat.items(), key=lambda kv: -len(kv[1])):
        groups = collections.defaultdict(list)
        for h in hs:
            groups[STRIP.sub('#', h['cmd'])[:80]].append(h)
        out.append(f"## {pat} — {len(hs):,} hits, {len(groups):,} distinct command groups")
        for i, g in enumerate(sorted(groups.values(), key=lambda v: -len(v))):
            if i >= a.max_groups:
                out.append(f"- … {len(groups) - a.max_groups} more groups omitted (see risky_cmds.jsonl)")
                break
            ts = sorted(x['ts'] or '' for x in g)
            projs = collections.Counter(x['project'] for x in g)
            flags = []
            if any(x['nested'] for x in g): flags.append('nested')
            if any(x['source'] == 'codex' for x in g): flags.append('codex')
            out.append(f"- ×{len(g)} · {ts[0][:16]} → {ts[-1][:16]} · projects {dict(projs.most_common(4))}{' · ' + ','.join(flags) if flags else ''}")
            for x in g[:a.examples]:
                out.append(f"    `{x['cmd'][:300].replace(chr(10), ' ⏎ ')}`  ({os.path.basename(x['path'])[:20]})")
        out.append("")
    open(os.path.join(a.work, 'risky_digest.md'), 'w').write('\n'.join(out) + '\n')
    print(f"{len(hits):,} hits, {len(by_pat)} patterns -> risky_digest.md", file=sys.stderr)


if __name__ == '__main__':
    main()
