#!/usr/bin/env python3
"""Aggregate work/sessions.jsonl (from quant.py) into the context files the lanes and red team read.
Usage: summarize.py ./work [--family-min 20] [--family-prefix 40]

Writes into the work dir:
  quant_summary.txt  totals by source, per project, per day, hour-of-day, session shapes, model mix,
                     tool calls, codex effort, repeated openers, biggest sessions
  automation.txt     automation families: opening prompts repeated >= --family-min times
  families.json      {family_prefix: [paths]} so sample.py can exclude robots from the human sample
All numbers are list-price shadow cost (see METHODOLOGY.md §2.1); say so wherever they are quoted.
"""
import os, sys, json, argparse, collections, datetime as dt, statistics


def load(work):
    return [json.loads(l) for l in open(os.path.join(work, 'sessions.jsonl'))]


def local_hour(ts):
    if not ts:
        return None
    try:
        t = dt.datetime.fromisoformat(ts.replace('Z', '+00:00'))
    except ValueError:
        return None
    return t.astimezone().hour, t.astimezone().weekday()


def dominant_model(rows):
    c = collections.Counter()
    for r in rows:
        for m, n in (r.get('models') or {}).items():
            c[m] += n
    return c.most_common(1)[0][0] if c else '?'


def money(x):
    return f"${x:,.0f}"


def families_of(rows, prefix_len, min_runs):
    groups = collections.defaultdict(list)
    for r in rows:
        if r['nested']:
            continue
        key = (r.get('first_prompt') or '')[:prefix_len].replace('\n', ' ').strip()
        if key:
            groups[key].append(r)
    return {k: v for k, v in groups.items() if len(v) >= min_runs}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('work')
    ap.add_argument('--family-min', type=int, default=20)
    ap.add_argument('--family-prefix', type=int, default=40)
    a = ap.parse_args()
    rows = load(a.work)
    top = [r for r in rows if not r['nested']]
    nested = [r for r in rows if r['nested']]
    fams = families_of(rows, a.family_prefix, a.family_min)
    fam_paths = {p for v in fams.values() for p in (r['path'] for r in v)}
    human = [r for r in top if r['path'] not in fam_paths and r['user_turns'] >= 1]

    out = []
    w = out.append
    days = sorted({(r['first_ts'] or '')[:10] for r in rows if r.get('first_ts')})
    w(f"# quant summary — {days[0] if days else '?'} .. {days[-1] if days else '?'} — generated by summarize.py")
    w("Costs are list-price shadow cost per M tokens (opus/fable 15/75, cache-write 18.75, cache-read 1.5; sonnet 3/15/3.75/0.3; haiku 1/5/1.25/0.1; gpt-5 class 1.25/10/1.25/0.125). "
      "cost_new = input + cache-write + output; cost_full adds cache reads. A comparison unit, not a bill.")
    w("")
    w("## Totals")
    for label, rs in (('all transcript files', rows), ('top-level sessions', top), ('sub-agent transcripts (nested)', nested),
                      ('human top-level sessions (>=1 user turn, not an automation family)', human)):
        if not rs:
            w(f"- {label}: 0"); continue
        w(f"- {label}: {len(rs):,} · new tokens {sum(r['new_tokens'] for r in rs)/1e6:,.0f}M · cache reads {sum(r['cache_read'] for r in rs)/1e6:,.0f}M · "
          f"cost_new {money(sum(r['cost_new'] for r in rs))} · cost_full {money(sum(r['cost_full'] for r in rs))}")
    for src in ('claude', 'codex'):
        rs = [r for r in top if r['source'] == src]
        if rs:
            w(f"- {src} top-level: {len(rs):,} sessions · cost_new {money(sum(r['cost_new'] for r in rs))} · cost_full {money(sum(r['cost_full'] for r in rs))} · "
              f"0 user turns: {sum(1 for r in rs if r['user_turns']==0):,} · <=1 user turn: {sum(1 for r in rs if r['user_turns']<=1):,}")
    w("")
    w("## Per project (top-level + nested, sorted by cost_full)")
    by_proj = collections.defaultdict(list)
    for r in rows:
        by_proj[r.get('project') or '?'].append(r)
    w("| project | sessions | nested | human | cost_new | cost_full | dominant model | codex share |")
    w("|---|---|---|---|---|---|---|---|")
    for proj, rs in sorted(by_proj.items(), key=lambda kv: -sum(r['cost_full'] for r in kv[1]))[:40]:
        h = sum(1 for r in rs if r['path'] in {x['path'] for x in human})
        cx = sum(1 for r in rs if r['source'] == 'codex')
        w(f"| {proj} | {sum(1 for r in rs if not r['nested']):,} | {sum(1 for r in rs if r['nested']):,} | {h:,} | {money(sum(r['cost_new'] for r in rs))} | {money(sum(r['cost_full'] for r in rs))} | {dominant_model(rs)} | {cx/len(rs)*100:.0f}% |")
    w("")
    w("## Per day (top-level sessions)")
    by_day = collections.defaultdict(list)
    for r in top:
        by_day[(r['first_ts'] or '')[:10]].append(r)
    for d in sorted(by_day):
        rs = by_day[d]
        w(f"- {d}: {len(rs):,} sessions ({sum(1 for r in rs if r['path'] in {x['path'] for x in human}):,} human) · cost_full {money(sum(r['cost_full'] for r in rs))}")
    w("")
    w("## Hour of day, human sessions (local machine time)")
    hours = collections.Counter(); wk = collections.Counter()
    for r in human:
        hw = local_hour(r['first_ts'])
        if hw:
            hours[hw[0]] += 1; wk['weekend' if hw[1] >= 5 else 'weekday'] += 1
    w(' '.join(f"{h:02d}:{hours[h]}" for h in range(24)))
    w(f"weekend share: {wk['weekend']/(sum(wk.values()) or 1)*100:.0f}%")
    w("")
    w("## Session shapes (human sessions)")
    durs = []
    for r in human:
        try:
            durs.append((dt.datetime.fromisoformat(r['last_ts'].replace('Z', '+00:00')) - dt.datetime.fromisoformat(r['first_ts'].replace('Z', '+00:00'))).total_seconds() / 3600)
        except Exception:
            pass
    if durs:
        durs.sort()
        w(f"- duration h: median {statistics.median(durs):.2f} · p90 {durs[int(len(durs)*0.9)]:.2f} · >8h {sum(1 for d in durs if d > 8)}")
    w(f"- >1,000 assistant turns: {sum(1 for r in human if r['assistant_turns'] > 1000)} · >100 assistant turns: {sum(1 for r in human if r['assistant_turns'] > 100)}")
    costs = sorted((r['cost_full'] for r in human), reverse=True)
    if costs:
        k = max(1, len(costs) // 100)
        w(f"- top 1% ({k}) sessions = {sum(costs[:k])/(sum(costs) or 1)*100:.0f}% of human cost_full · biggest {money(costs[0])}")
    w(f"- interrupts total {sum(r['interrupts'] for r in human):,} · api errors {sum(r['api_errors'] for r in human):,} · short openers (<60 chars) {sum(r['short_openers'] for r in human):,} · plan-mode mentions {sum(r['plan_mode'] for r in human):,} · effort words {sum(r['effort_words'] for r in human):,}")
    w("")
    w("## Model mix (all files, cost_full)")
    mm = collections.defaultdict(float)
    for r in rows:
        for m, tk in (r.get('tok') or {}).items():
            mm[m] += r['cost_full'] * ((tk[0] + tk[1] + tk[2] + tk[3]) / (max(1, sum(sum(v) for v in r['tok'].values()))))
    tot = sum(mm.values()) or 1
    for m, c in sorted(mm.items(), key=lambda kv: -kv[1])[:12]:
        w(f"- {m}: {money(c)} ({c/tot*100:.0f}%)")
    w("")
    w("## Tool calls (all files)")
    tc = collections.Counter()
    for r in rows:
        for t, n in (r.get('tools') or {}).items():
            tc[t] += n
    w(', '.join(f"{t} {n:,}" for t, n in tc.most_common(25)))
    w("")
    eff = collections.Counter(r.get('reasoning_effort') or '?' for r in top if r['source'] == 'codex')
    orig = collections.Counter(r.get('originator') or '?' for r in top if r['source'] == 'codex')
    if eff:
        w("## Codex")
        w(f"- effort: {dict(eff.most_common())} · originator: {dict(orig.most_common())}")
        w("")
    w("## Automation families (opening prompt repeated >= %d times, first %d chars)" % (a.family_min, a.family_prefix))
    w(f"{len(fams)} families, {len(fam_paths):,} sessions, cost_full {money(sum(r['cost_full'] for v in fams.values() for r in v))} — details in automation.txt")
    w("")
    w("## Biggest top-level sessions (cost_full)")
    for r in sorted(top, key=lambda r: -r['cost_full'])[:15]:
        w(f"- {money(r['cost_full'])} · {r['source']} · {r.get('project')} · {(r['first_ts'] or '')[:16]} · user {r['user_turns']} / asst {r['assistant_turns']} · {r['session_id']} · {(r.get('first_prompt') or '')[:70].replace(chr(10),' ')!r}")
    open(os.path.join(a.work, 'quant_summary.txt'), 'w').write('\n'.join(out) + '\n')

    fo = ["# automation families — opening prompt repeated >= %d times (first %d chars). Generated by summarize.py" % (a.family_min, a.family_prefix),
          "Watch for framework boilerplate masquerading as a family (e.g. a plugin stub as first user message) and for teammate traffic counted as user turns.", "",
          "| family (opening prefix) | runs | new tokens | cost_new | cost_full | share of all cost_full | dominant model | source |", "|---|---|---|---|---|---|---|---|"]
    all_cost = sum(r['cost_full'] for r in rows) or 1
    for k, v in sorted(fams.items(), key=lambda kv: -len(kv[1])):
        fo.append(f"| {k.replace('|', '/')} | {len(v):,} | {sum(r['new_tokens'] for r in v)/1e6:,.1f}M | {money(sum(r['cost_new'] for r in v))} | {money(sum(r['cost_full'] for r in v))} | {sum(r['cost_full'] for r in v)/all_cost*100:.1f}% | {dominant_model(v)} | {collections.Counter(r['source'] for r in v).most_common(1)[0][0]} |")
    open(os.path.join(a.work, 'automation.txt'), 'w').write('\n'.join(fo) + '\n')
    json.dump({k: [r['path'] for r in v] for k, v in fams.items()}, open(os.path.join(a.work, 'families.json'), 'w'), indent=0)
    print(f"sessions {len(rows):,} (top {len(top):,}, nested {len(nested):,}), human {len(human):,}, families {len(fams)} covering {len(fam_paths):,} sessions", file=sys.stderr)


if __name__ == '__main__':
    main()
