"""Frozen pricing table — GENERATED by generate_pricing.py, do not hand-edit.

Source: litellm_snapshot.json (vendored LiteLLM registry, first-party
anthropic claude entries) + pricing_overrides.json (dated regimes).
USD per million tokens.

Invariant corrections applied (registry cache_1h was corrupt, corrected
to 2x input per Anthropic's documented rule):
- claude-3-haiku-20240307: cache_1h 6.0 -> 0.5 (registry value violated cache_1h>=cache_5m or +/-10% of 2x input=0.5)
- claude-3-opus-20240229: cache_1h 6.0 -> 30.0 (registry value violated cache_1h>=cache_5m or +/-10% of 2x input=30.0)
"""

SNAPSHOT_VENDORED_AT = "2026-08-02"

PRICING_BY_MODEL = {
    "claude-3-7-sonnet-20250219": {
        "cache_1h": 6.0,
        "cache_5m": 3.75,
        "cache_read": 0.3,
        "in": 3.0,
        "out": 15.0
    },
    "claude-3-haiku-20240307": {
        "cache_1h": 0.5,
        "cache_5m": 0.3,
        "cache_read": 0.03,
        "in": 0.25,
        "out": 1.25
    },
    "claude-3-opus-20240229": {
        "cache_1h": 30.0,
        "cache_5m": 18.75,
        "cache_read": 1.5,
        "in": 15.0,
        "out": 75.0
    },
    "claude-4-opus-20250514": {
        "cache_1h": 30.0,
        "cache_5m": 18.75,
        "cache_read": 1.5,
        "in": 15.0,
        "out": 75.0
    },
    "claude-4-sonnet-20250514": {
        "cache_1h": 6.0,
        "cache_5m": 3.75,
        "cache_5m_200k": 7.5,
        "cache_read": 0.3,
        "cache_read_200k": 0.6,
        "in": 3.0,
        "in_200k": 6.0,
        "out": 15.0,
        "out_200k": 22.5
    },
    "claude-fable-5": {
        "cache_1h": 20.0,
        "cache_5m": 12.5,
        "cache_read": 1.0,
        "in": 10.0,
        "out": 50.0
    },
    "claude-haiku-4-5": {
        "cache_1h": 2.0,
        "cache_5m": 1.25,
        "cache_read": 0.1,
        "in": 1.0,
        "out": 5.0
    },
    "claude-haiku-4-5-20251001": {
        "cache_1h": 2.0,
        "cache_5m": 1.25,
        "cache_read": 0.1,
        "in": 1.0,
        "out": 5.0
    },
    "claude-opus-4-1": {
        "cache_1h": 30.0,
        "cache_5m": 18.75,
        "cache_read": 1.5,
        "in": 15.0,
        "out": 75.0
    },
    "claude-opus-4-1-20250805": {
        "cache_1h": 30.0,
        "cache_5m": 18.75,
        "cache_read": 1.5,
        "in": 15.0,
        "out": 75.0
    },
    "claude-opus-4-20250514": {
        "cache_1h": 30.0,
        "cache_5m": 18.75,
        "cache_read": 1.5,
        "in": 15.0,
        "out": 75.0
    },
    "claude-opus-4-5": {
        "cache_1h": 10.0,
        "cache_5m": 6.25,
        "cache_read": 0.5,
        "in": 5.0,
        "out": 25.0
    },
    "claude-opus-4-5-20251101": {
        "cache_1h": 10.0,
        "cache_5m": 6.25,
        "cache_read": 0.5,
        "in": 5.0,
        "out": 25.0
    },
    "claude-opus-4-6": {
        "cache_1h": 10.0,
        "cache_5m": 6.25,
        "cache_read": 0.5,
        "in": 5.0,
        "out": 25.0
    },
    "claude-opus-4-6-20260205": {
        "cache_1h": 10.0,
        "cache_5m": 6.25,
        "cache_read": 0.5,
        "in": 5.0,
        "out": 25.0
    },
    "claude-opus-4-7": {
        "cache_1h": 10.0,
        "cache_5m": 6.25,
        "cache_read": 0.5,
        "in": 5.0,
        "out": 25.0
    },
    "claude-opus-4-7-20260416": {
        "cache_1h": 10.0,
        "cache_5m": 6.25,
        "cache_read": 0.5,
        "in": 5.0,
        "out": 25.0
    },
    "claude-opus-4-8": {
        "cache_1h": 10.0,
        "cache_5m": 6.25,
        "cache_read": 0.5,
        "in": 5.0,
        "out": 25.0
    },
    "claude-opus-5": {
        "cache_1h": 10.0,
        "cache_5m": 6.25,
        "cache_read": 0.5,
        "in": 5.0,
        "out": 25.0
    },
    "claude-sonnet-4-20250514": {
        "cache_1h": 6.0,
        "cache_5m": 3.75,
        "cache_5m_200k": 7.5,
        "cache_read": 0.3,
        "cache_read_200k": 0.6,
        "in": 3.0,
        "in_200k": 6.0,
        "out": 15.0,
        "out_200k": 22.5
    },
    "claude-sonnet-4-5": {
        "cache_1h": 6.0,
        "cache_1h_200k": 12.0,
        "cache_5m": 3.75,
        "cache_5m_200k": 7.5,
        "cache_read": 0.3,
        "cache_read_200k": 0.6,
        "in": 3.0,
        "in_200k": 6.0,
        "out": 15.0,
        "out_200k": 22.5
    },
    "claude-sonnet-4-5-20250929": {
        "cache_1h": 6.0,
        "cache_1h_200k": 12.0,
        "cache_5m": 3.75,
        "cache_5m_200k": 7.5,
        "cache_read": 0.3,
        "cache_read_200k": 0.6,
        "in": 3.0,
        "in_200k": 6.0,
        "out": 15.0,
        "out_200k": 22.5
    },
    "claude-sonnet-4-6": {
        "cache_1h": 6.0,
        "cache_5m": 3.75,
        "cache_read": 0.3,
        "in": 3.0,
        "out": 15.0
    },
    "claude-sonnet-5": {
        "cache_1h": 4.0,
        "cache_5m": 2.5,
        "cache_read": 0.2,
        "in": 2.0,
        "out": 10.0
    }
}

PRICING_BY_FAMILY = {
    "fable": {
        "cache_1h": 20.0,
        "cache_5m": 12.5,
        "cache_read": 1.0,
        "in": 10.0,
        "out": 50.0
    },
    "haiku": {
        "cache_1h": 2.0,
        "cache_5m": 1.25,
        "cache_read": 0.1,
        "in": 1.0,
        "out": 5.0
    },
    "opus": {
        "cache_1h": 10.0,
        "cache_5m": 6.25,
        "cache_read": 0.5,
        "in": 5.0,
        "out": 25.0
    },
    "sonnet": {
        "cache_1h": 4.0,
        "cache_5m": 2.5,
        "cache_read": 0.2,
        "in": 2.0,
        "out": 10.0
    }
}

PRICING_DATED = [
    {
        "effective_from": None,
        "effective_until": "2026-08-31T23:59:59Z",
        "model": "claude-sonnet-5",
        "rates": {
            "cache_1h": 4.0,
            "cache_5m": 2.5,
            "cache_read": 0.2,
            "in": 2.0,
            "out": 10.0
        }
    },
    {
        "effective_from": "2026-09-01T00:00:00Z",
        "effective_until": None,
        "model": "claude-sonnet-5",
        "rates": {
            "cache_1h": 6.0,
            "cache_5m": 3.75,
            "cache_read": 0.3,
            "in": 3.0,
            "out": 15.0
        }
    }
]
